{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Established TCP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab{}", "legendFormat": "Estab TCP" }
   ]
  },
  {
   "title": "packet in out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_IpExt_InOctets{job=\"nodeexporter_local\"}[$__interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_netstat_IpExt_OutOctets{}[$__interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "BroadCast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "packets" }
   ],
   "targets": [
    {
     "expr": "netdata_ip_bcastpkts_packets_persec_average{instance=\"netdata:19999\"}",
     "legendFormat": "{{dimension}}"
    },
    {}
   ]
  },
  {
   "title": "MultiCast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netdata_ip_mcastpkts_packets_persec_average{instance=\"netdata:19999\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Packet error\\drop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_stat_drop{instance=\"netdata:9100\"}",
     "legendFormat": "drop"
    },
    {
     "expr": "node_network_transmit_errs_total{device=\"eth0\",instance=\"netdata:9100\"}",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "forward packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Ip_Forwarding{job=\"nodeexporter_local\"}[$__interval])",
     "legendFormat": "Forw"
    }
   ]
  }
 ]
}