# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false
  config.vm.define "laband" do |laband|
	laband.vm.network "forwarded_port", guest: 22, host: 2266
	laband.vm.network "forwarded_port", guest: 5000, host: 5000
	laband.vm.provision :ansible_local do |ansible|
	  ansible.verbose = true
		ansible.install = true		
		ansible.playbook = "playbook.yml"
		ansible.limit = "all"

		end
	end
	
end 
